### ISSUE TITLE
Latest code not work properly

### ISSUE THREAD

**Issue by HADB** [LittleSource/ssml-editor#1]
Latest code seems having some bugs and not work properly, any updates? Thanks a lot!

**Comment by LittleSource** [comment]
Where is the bug, please provide valid context to explain in detail

**Comment by HADB** [comment]
<img width="1398" alt="iShot_2023-09-01_10 42 08" src="https://github.com/LittleSource/ssml-editor/assets/1836701/bf7fdb7e-23b8-48ee-a011-d0e3c3a89d8e">

操作的话基本上UI上不太对劲，会换行，设置多音字的时候文字也会被替换没，控制台发现有些报错

**Comment by LittleSource** [comment]
我修复了ui等一些问题，但是还有一些其他问题等我有时间了再改或者你可以提PR
